name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.14', '1.15' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Debug Vim version
        run: vim --version
      - name: Install gosumcheck
        run: env GO111MODULE=off go get github.com/haya14busa/gosum/cmd/gosumcheck
      - name: Test
        run: go test -v -race ./...
      - name: Check code generation diff
        run: bash go/generate.sh && ! git diff | grep '^'
      - name: Check gosumcheck
        run: gosumcheck ./...
