name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.18' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Debug Vim version
        run: vim --version
      - name: Test
        run: go test -v -race -coverpkg=./... -coverprofile=coverage.txt ./...
      - name: Check code generation diff
        run: bash go/generate.sh && ! git diff | grep '^'
      - name: Report coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.txt
